stages:
  - build-image
  - deploy


create image:
  stage: build-image
#  tags: 
#    - local
#  image: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
#    - pwd
#    - ls -la
#    - systemctl start docker
#    - systemctl status docker
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

deploy-local:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - main
  script:
    - kubectl apply -f k8s/deployment.yaml -n prometheus
    - kubectl apply -f k8s/service.yaml -n prometheus
    - kubectl apply -f k8s/ingress.yaml -n prometheus
    - kubectl set image deployment/prometheus-rancher-exporter-deployment -n=prometheus prometheus-rancher-exporter=git.mos.ru:5050/datacenter/cod-linux/rancher_exporter:${CI_PIPELINE_ID}
    - kubectl rollout restart deployment/prometheus-rancher-exporter-deployment -n prometheus
